//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public int BrdID { get; set; }
        public string cType { get; set; }
        public string BrandName { get; set; }
        public string Item { get; set; }
        public Nullable<int> SLNO { get; set; }
        public Nullable<int> TAT { get; set; }
        public string BCode { get; set; }
        public Nullable<int> Tag { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
