//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashSale
    {
        public int JobID { get; set; }
        public string MRNO { get; set; }
        public string JobCode { get; set; }
        public string Branch { get; set; }
        public string CustName { get; set; }
        public string CustAddress1 { get; set; }
        public string CustAddress2 { get; set; }
        public string Brand { get; set; }
        public string ModelNo { get; set; }
        public string ESN { get; set; }
        public string SLNo { get; set; }
        public Nullable<System.DateTime> ReceptDate { get; set; }
        public string ReceptBy { get; set; }
        public string Code { get; set; }
        public string ProdName { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> PrdAmt { get; set; }
        public Nullable<double> Dis { get; set; }
        public Nullable<double> NetAmnt { get; set; }
        public string Log_User { get; set; }
        public Nullable<System.DateTime> Log_Date { get; set; }
        public Nullable<int> DFlag { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}
