//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cType
    {
        public int AutoNmbr { get; set; }
        public string cTypeName { get; set; }
        public string cCode { get; set; }
        public Nullable<int> DMSCatID { get; set; }
    }
}
