//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimateRefused
    {
        public int EstRAID { get; set; }
        public string JobCode { get; set; }
        public string ServiceBy_ID { get; set; }
        public Nullable<System.DateTime> EstDate { get; set; }
        public string EstText { get; set; }
        public Nullable<double> RefuseAmnt { get; set; }
        public string Branch { get; set; }
    }
}
