//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryFindProduct1
    {
        public string JobCode { get; set; }
        public string Branch { get; set; }
        public string CustName { get; set; }
        public string CustAddress1 { get; set; }
        public string CustAddress2 { get; set; }
        public string Brand { get; set; }
        public string ModelNo { get; set; }
        public string SLNo { get; set; }
        public Nullable<System.DateTime> ReceptDate { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string ReceptBy { get; set; }
        public string IssueTo { get; set; }
        public Nullable<System.DateTime> IsssueDate { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public string ServiceBy { get; set; }
        public Nullable<System.DateTime> DDate { get; set; }
        public string DeliverBy { get; set; }
        public string Code { get; set; }
        public string ProdName { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> UnitPrice { get; set; }
    }
}
