//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryGrade
    {
        public string JobCode { get; set; }
        public string Branch { get; set; }
        public string CustName { get; set; }
        public string CustAddress1 { get; set; }
        public string CustAddress2 { get; set; }
        public string Brand { get; set; }
        public string ModelNo { get; set; }
        public string SLNo { get; set; }
        public Nullable<System.DateTime> ReceptDate { get; set; }
        public Nullable<double> SvAmt { get; set; }
        public Nullable<double> PrdAmt { get; set; }
        public Nullable<double> OtherAmt { get; set; }
        public Nullable<double> Dis { get; set; }
        public string cGrade { get; set; }
        public string cRemarks { get; set; }
        public string MRNO { get; set; }
        public Nullable<int> WCondition { get; set; }
        public Nullable<System.DateTime> DDate { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public string IssueTo { get; set; }
        public Nullable<System.DateTime> IsssueDate { get; set; }
        public string ReceptBy { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<int> cFlag { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
