//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryRptClaimInfo
    {
        public int JobID { get; set; }
        public string JobCode { get; set; }
        public string CustName { get; set; }
        public string CustAddress1 { get; set; }
        public string CustAddress2 { get; set; }
        public string ModelNo { get; set; }
        public string SLNo { get; set; }
        public Nullable<System.DateTime> ReceptDate { get; set; }
        public Nullable<System.DateTime> AppDelDate { get; set; }
        public string ServiceType { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public string ServiceBy { get; set; }
        public Nullable<System.DateTime> DDate { get; set; }
        public Nullable<int> cFlag { get; set; }
        public string ClaimCode { get; set; }
    }
}
