//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Replace
    {
        public int ClaimID { get; set; }
        public string JobCode { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string ESN { get; set; }
        public string ESNb { get; set; }
        public string SLNo { get; set; }
        public string Other { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
        public string ReplaceBy { get; set; }
    }
}
