//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceItem
    {
        public long SrvID { get; set; }
        public string JobCode { get; set; }
        public string Item { get; set; }
        public Nullable<int> ItemCode { get; set; }
    }
}
