//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftUser
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Passward { get; set; }
        public Nullable<int> sTag { get; set; }
        public string WebAccess { get; set; }
        public string WebAccessType { get; set; }
        public string UserType { get; set; }
        public Nullable<int> EID { get; set; }
        public string eName { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> ChngPass { get; set; }
        public string BranchEmail { get; set; }
    }
}
