//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBill_FFC
    {
        public int TBFCID { get; set; }
        public string JobNO { get; set; }
        public Nullable<int> FaultCharge { get; set; }
        public Nullable<int> ServiceCharge { get; set; }
    }
}
