//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGrade
    {
        public int ID { get; set; }
        public string JobCode { get; set; }
        public string cGrade { get; set; }
        public string cRemarks { get; set; }
    }
}
