//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RptTechnicianPerformance
    {
        public int TPID { get; set; }
        public string Name { get; set; }
        public Nullable<int> FirstSlab { get; set; }
        public Nullable<int> SecondSlab { get; set; }
        public Nullable<int> ThirdSlab { get; set; }
        public Nullable<int> FourSlave { get; set; }
        public Nullable<int> FiveSlab { get; set; }
        public Nullable<int> SixSlab { get; set; }
        public Nullable<int> SevenSlab { get; set; }
    }
}
