//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDailyInOut
    {
        public int DIOID { get; set; }
        public Nullable<System.DateTime> tDate { get; set; }
        public string RvJobNo { get; set; }
        public string RvBrand { get; set; }
        public string RvModel { get; set; }
        public string RvESN { get; set; }
        public string RvCust { get; set; }
        public Nullable<int> RvStatus { get; set; }
        public string RpJobNo { get; set; }
        public string RpBrand { get; set; }
        public string RpModel { get; set; }
        public string RpESN { get; set; }
        public string RpCust { get; set; }
        public Nullable<int> RpStatus { get; set; }
        public Nullable<int> RpCFlag { get; set; }
        public string DvJobNo { get; set; }
        public string DvBrand { get; set; }
        public string DvModel { get; set; }
        public string DvESN { get; set; }
        public string DvCust { get; set; }
        public Nullable<int> DvStatus { get; set; }
        public Nullable<double> DvAmt { get; set; }
        public Nullable<int> DvcFlag { get; set; }
        public Nullable<int> TAT { get; set; }
        public string PenJobNo { get; set; }
        public string PenBrand { get; set; }
        public string PenModel { get; set; }
    }
}
