//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSMSReceipentList
    {
        public int RAID { get; set; }
        public string RName { get; set; }
        public string ContactNo { get; set; }
        public string LocalNo { get; set; }
        public string SingNo { get; set; }
        public string ThaiNo { get; set; }
        public string IndoNo { get; set; }
        public Nullable<int> rActive { get; set; }
    }
}
