//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStoregeSET
    {
        public int SSID { get; set; }
        public string JobCode { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string Bin { get; set; }
        public string Remarks { get; set; }
        public string Branch { get; set; }
    }
}
