//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTechPerformancSummary
    {
        public int TPSID { get; set; }
        public string TechName { get; set; }
        public string Category { get; set; }
        public Nullable<int> TR { get; set; }
        public Nullable<int> WR { get; set; }
        public Nullable<int> OP { get; set; }
        public Nullable<int> D { get; set; }
        public Nullable<int> WD { get; set; }
        public Nullable<int> UP { get; set; }
        public Nullable<int> P { get; set; }
        public Nullable<int> NR { get; set; }
        public Nullable<int> NRD { get; set; }
        public Nullable<int> RL { get; set; }
        public Nullable<int> WRL { get; set; }
        public Nullable<int> CR { get; set; }
        public Nullable<int> CRD { get; set; }
        public Nullable<int> SW { get; set; }
    }
}
