//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempService
    {
        public int TSID { get; set; }
        public string JobNo { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public string Branch { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string AssignTo { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public string ServiceBy { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
    }
}
