//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempMIS_Report
    {
        public int MISRID { get; set; }
        public string Branch { get; set; }
        public Nullable<int> RecTotal { get; set; }
        public Nullable<int> RecTotalP { get; set; }
        public Nullable<int> RecMAvg { get; set; }
        public Nullable<int> RecMAvgP { get; set; }
        public Nullable<int> DelNW { get; set; }
        public Nullable<int> DelNWP { get; set; }
        public Nullable<int> DelSlsW { get; set; }
        public Nullable<int> DelSlsWP { get; set; }
        public Nullable<int> DelSvcW { get; set; }
        public Nullable<int> DelSvcWP { get; set; }
        public Nullable<int> DelMAvg { get; set; }
        public Nullable<int> DelMAvgP { get; set; }
        public Nullable<int> DelSonyItem { get; set; }
        public Nullable<int> DelSonyItemP { get; set; }
        public Nullable<double> NWAmnt { get; set; }
        public Nullable<double> NWAmntP { get; set; }
        public Nullable<double> WAmnt { get; set; }
        public Nullable<double> WAmntP { get; set; }
        public Nullable<double> SCCollectionAmnt { get; set; }
        public Nullable<double> SCCollectionAmntP { get; set; }
        public Nullable<double> VirtualAmnt { get; set; }
        public Nullable<double> VirtualAmntP { get; set; }
        public Nullable<double> DisAmnt { get; set; }
        public Nullable<double> DisAmntP { get; set; }
        public Nullable<double> CollectionAmnt { get; set; }
        public Nullable<double> CollectionAmntP { get; set; }
        public Nullable<int> CountOfMonth { get; set; }
        public Nullable<double> AdvAmnt { get; set; }
        public Nullable<double> AdvAmntP { get; set; }
    }
}
