//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferJob
    {
        public int TrID { get; set; }
        public string JobCode { get; set; }
        public string Remarks { get; set; }
        public string TransferFrom { get; set; }
        public string TransferTo { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string TrByCode { get; set; }
        public string TrByName { get; set; }
    }
}
