//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Advance_Info
    {
        public int AdvAID { get; set; }
        public string JobCode { get; set; }
        public string Branch { get; set; }
        public string CustName { get; set; }
        public string CustAddress1 { get; set; }
        public string CustAddress2 { get; set; }
        public string ModelNo { get; set; }
        public string Brand { get; set; }
        public string SLNo { get; set; }
        public Nullable<System.DateTime> ReceptDate { get; set; }
        public string AdvNo { get; set; }
        public Nullable<System.DateTime> AdvDate { get; set; }
        public Nullable<double> AdvAmnt { get; set; }
        public string AdvRemarks { get; set; }
        public string PayType { get; set; }
        public string BankName { get; set; }
        public string CardNo { get; set; }
    }
}
