//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TransferJob
    {
        public string JobCode { get; set; }
        public string TransferFrom { get; set; }
        public string TransferTo { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string TrByCode { get; set; }
        public string TrByName { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> WCondition { get; set; }
        public Nullable<int> cFlag { get; set; }
        public string Brand { get; set; }
        public string ModelNo { get; set; }
        public string SLNo { get; set; }
        public string cType { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<System.DateTime> DDate { get; set; }
        public Nullable<System.DateTime> ReceptDate { get; set; }
    }
}
